<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Table\Api\Representation\TableRepresentation $table
 * @var \Table\Api\Representation\TableRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'tables show');

$this->headLink()
    ->appendStylesheet($assetUrl('css/table.css', 'Table'));

$owner = $table->owner();
?>

<?= $this->pageTitle($table->displayTitle(), 1, $translate('Tables')) ?>

<div id="page-actions">
    <?php if ($table->userIsAllowed('update')): ?>
    <?= $table->link($translate('Edit table'), 'edit', ['class' => 'button']) ?>
    <?php endif; ?>
</div>

<?php $this->trigger('view.show.before'); ?>

<div id="item-metadata">
    <dl class="table-resource">
        <div class="meta-group">
            <dt><?= $translate('ID') ?></dt>
            <dd class="value"><?= $table->id() ?></dd>
            <dt><?= $translate('Owner') ?></dt>
            <dd class="value"><?= $owner ? $escape($owner->name()) : $translate('None') ?></dd>
            <dt><?= $translate('Slug') ?></dt>
            <dd class="value"><?= $escape($table->slug()) ?></dd>
            <?php if ($v = $table->lang()): ?>
            <dt><?= $translate('Language') ?></dt>
            <dd class="value"><?= $escape($v) ?></dd>
            <?php endif; ?>
            <?php if ($v = $table->source()): ?>
            <dt><?= $translate('Source') ?></dt>
            <dd class="value"><?= $escape($v) ?></dd>
            <?php endif; ?>
            <?php if ($v = $table->comment()): ?>
            <dt><?= $translate('Comment') ?></dt>
            <dd class="value"><?= $escape($v) ?></dd>
            <?php endif; ?>
            <dt><?= $translate('Created') ?></dt>
            <dd class="value"><?= $escape($i18n->dateFormat($table->created())) ?></dd>
            <?php if ($modified = $table->modified()): ?>
            <dt><?= $translate('Modified') ?></dt>
            <dd class="value"><?= $escape($i18n->dateFormat($modified)) ?></dd>
            <?php endif; ?>
        </div>
    </dl>
    <?php if ($table->codeCount()): ?>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <th><?= $translate('Code') ?></th>
            <th><?= $translate('Label') ?></th>
        </thead>
        <tbody>
            <?php foreach($table->codes() as $code => $label): ?>
            <tr>
                <td><?= $escape($code) ?></td>
                <td><?= $escape($label) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php else: ?>
    <p><?= $translate('No codes') ?></p>
    <?php endif; ?>
</div>

<?php $this->trigger('view.show.after'); ?>
