<?php declare(strict_types=1);

namespace TableTest\Api;

use CommonTest\AbstractHttpControllerTestCase;
use TableTest\TableTestTrait;

/**
 * Tests for the Table API (CRUD operations).
 */
class TableApiTest extends AbstractHttpControllerTestCase
{
    use TableTestTrait;

    public function setUp(): void
    {
        parent::setUp();
        $this->loginAdmin();
    }

    public function tearDown(): void
    {
        $this->cleanupTables();
        parent::tearDown();
    }

    /**
     * Test creating a simple associative table.
     */
    public function testCreateAssociativeTable(): void
    {
        $table = $this->createAssociativeTable('Countries', [
            'FR' => 'France',
            'DE' => 'Germany',
            'ES' => 'Spain',
        ]);

        $this->assertNotNull($table->id());
        $this->assertEquals('Countries', $table->title());
        $this->assertTrue($table->isAssociative());
        $this->assertEquals(3, $table->codeCount());
    }

    /**
     * Test creating a table with slug.
     */
    public function testCreateTableWithSlug(): void
    {
        $table = $this->createTable([
            'o:title' => 'My Custom Table',
            'o:slug' => 'my-custom-slug',
            'o:is_associative' => true,
            'o:codes' => [
                ['code' => 'a', 'label' => 'Alpha'],
            ],
        ]);

        $this->assertEquals('my-custom-slug', $table->slug());
    }

    /**
     * Test that slug is auto-generated from title.
     */
    public function testSlugAutoGeneratedFromTitle(): void
    {
        $table = $this->createTable([
            'o:title' => 'Auto Generated Slug',
            'o:is_associative' => true,
            'o:codes' => [],
        ]);

        $this->assertNotEmpty($table->slug());
        $this->assertStringContainsString('auto', $table->slug());
    }

    /**
     * Test creating a multilingual table.
     */
    public function testCreateMultilingualTable(): void
    {
        $table = $this->createMultilingualTable('Greetings', [
            ['code' => 'hello', 'label' => 'Hello'],
            ['code' => 'hello', 'label' => 'Bonjour'],
            ['code' => 'hello', 'label' => 'Hola'],
            ['code' => 'goodbye', 'label' => 'Goodbye'],
            ['code' => 'goodbye', 'label' => 'Au revoir'],
        ]);

        $this->assertFalse($table->isAssociative());
        // 5 code entries but only 2 unique codes.
        $codes = $table->codes();
        $this->assertCount(2, $codes);
        $this->assertArrayHasKey('hello', $codes);
        $this->assertArrayHasKey('goodbye', $codes);
    }

    /**
     * Test updating a table.
     */
    public function testUpdateTable(): void
    {
        $table = $this->createAssociativeTable('Original Title', [
            'a' => 'Alpha',
        ]);

        $updated = $this->api()->update('tables', $table->id(), [
            'o:title' => 'Updated Title',
        ], [], ['isPartial' => true])->getContent();

        $this->assertEquals('Updated Title', $updated->title());
    }

    /**
     * Test updating table codes.
     */
    public function testUpdateTableCodes(): void
    {
        $table = $this->createAssociativeTable('Codes Test', [
            'a' => 'Alpha',
            'b' => 'Beta',
        ]);

        $this->assertEquals(2, $table->codeCount());

        $updated = $this->api()->update('tables', $table->id(), [
            'o:codes' => [
                ['code' => 'a', 'label' => 'Alpha Updated'],
                ['code' => 'b', 'label' => 'Beta'],
                ['code' => 'c', 'label' => 'Gamma'],
            ],
        ], [], ['isPartial' => true])->getContent();

        $this->assertEquals(3, $updated->codeCount());
        $this->assertEquals('Alpha Updated', $updated->labelFromCode('a'));
    }

    /**
     * Test deleting a table.
     */
    public function testDeleteTable(): void
    {
        $table = $this->createAssociativeTable('To Delete', ['x' => 'X']);
        $tableId = $table->id();

        // Remove from cleanup list since we're deleting it manually.
        $this->createdTables = array_diff($this->createdTables, [$tableId]);

        $this->api()->delete('tables', $tableId);

        $this->expectException(\Omeka\Api\Exception\NotFoundException::class);
        $this->api()->read('tables', $tableId);
    }

    /**
     * Test searching tables by title.
     */
    public function testSearchTablesByTitle(): void
    {
        $this->createAssociativeTable('Unique Search Title ABC', ['a' => 'A']);
        $this->createAssociativeTable('Another Table', ['b' => 'B']);

        $results = $this->api()->search('tables', [
            'title' => 'Unique Search Title ABC',
        ])->getContent();

        $this->assertCount(1, $results);
        $this->assertEquals('Unique Search Title ABC', $results[0]->title());
    }

    /**
     * Test searching tables by slug.
     */
    public function testSearchTablesBySlug(): void
    {
        $table = $this->createTable([
            'o:title' => 'Slug Search Test',
            'o:slug' => 'unique-search-slug',
            'o:is_associative' => true,
            'o:codes' => [],
        ]);

        $results = $this->api()->search('tables', [
            'slug' => 'unique-search-slug',
        ])->getContent();

        $this->assertCount(1, $results);
        $this->assertEquals($table->id(), $results[0]->id());
    }

    /**
     * Test that duplicate slugs are rejected.
     */
    public function testDuplicateSlugsRejected(): void
    {
        $this->createTable([
            'o:title' => 'First Table',
            'o:slug' => 'duplicate-slug-test',
            'o:is_associative' => true,
            'o:codes' => [],
        ]);

        $this->expectException(\Omeka\Api\Exception\ValidationException::class);

        $this->createTable([
            'o:title' => 'Second Table',
            'o:slug' => 'duplicate-slug-test',
            'o:is_associative' => true,
            'o:codes' => [],
        ]);
    }

    /**
     * Test that table requires a title.
     */
    public function testTableRequiresTitle(): void
    {
        $this->expectException(\Omeka\Api\Exception\ValidationException::class);

        $this->createTable([
            'o:title' => '',
            'o:is_associative' => true,
            'o:codes' => [],
        ]);
    }

    /**
     * Test reading table by slug.
     */
    public function testReadTableBySlug(): void
    {
        $table = $this->createTable([
            'o:title' => 'Read By Slug Test',
            'o:slug' => 'read-by-slug-test',
            'o:is_associative' => true,
            'o:codes' => [['code' => 'x', 'label' => 'X']],
        ]);

        $found = $this->api()->read('tables', ['slug' => 'read-by-slug-test'])->getContent();

        $this->assertEquals($table->id(), $found->id());
    }
}
